FROM nginx:1.27-alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY index.html /usr/share/nginx/html/
COPY static/ /usr/share/nginx/html/static/
COPY docker-entrypoint.sh /docker-entrypoint.d/40-pizza-config.sh
RUN chmod +x /docker-entrypoint.d/40-pizza-config.sh

EXPOSE 80
