version: '3'
services:
  db:
    image: postgres:10.1-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pizza-dev
    volumes:
      - ./.docker_volumes/pg:/var/lib/postgresql/data
  web:
    build: ./web
    command: live-server --port=8080 --host=0.0.0.0 --verbose
    restart: always
    depends_on:
      - api
    volumes:
      - ./web:/app
    ports:
      - "8080:8080"
    links:
      - api
  api:
    build: ./api
    restart: always
    depends_on:
      - db
    command: start-dev
    volumes:
      - ./api:/app
    ports:
      - "8000:8000"
    environment:
      DJANGO_ENV: dev
      DB_NAME: pizza-dev
      DB_USER: postgres
      DB_PASS: password
      DB_HOST: db
    links:
      - db
