# Generated by Django 2.0.2 on 2018-02-17 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('R', 'Order received'), ('P', 'Order being prepared'), ('O', 'On its way'), ('D', 'Delivered')], default='R', max_length=1),
        ),
    ]
